# Hardware configuration — auto-generated by nixos-generate-config on the target system
# This placeholder will be overwritten during NixOS installation.
# See Phase 1.3 in the migration plan for generation instructions.

{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [ ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "uas" "sd_mod"];
  boot.initrd.kernelModules = ["dm-snapshot" "amdgpu"];
  boot.kernelModules = ["kvm-amd" "thinkpad_acpi"];

  # NOTE: Update this UUID after installation with your actual LUKS partition UUID
  # boot.initrd.luks.devices."root" = {
  #   device = "/dev/disk/by-uuid/YOUR-UUID-HERE";
  #   allowDiscards = true;
  #   bypassWorkqueues = true;
  # };

  # NOTE: Update these UUIDs after installation
  fileSystems."/" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = ["subvol=@root" "compress=zstd:3" "noatime" "ssd"];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = ["subvol=@home" "compress=zstd:3" "noatime" "ssd"];
  };

  fileSystems."/var/log" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = ["subvol=@log" "compress=zstd:3" "noatime" "ssd"];
    neededForBoot = true;
  };

  fileSystems."/var/cache" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = ["subvol=@cache" "compress=zstd:3" "noatime" "ssd"];
  };

  fileSystems."/swap" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = ["subvol=@swap" "noatime" "nodatacow"];
  };

  # NOTE: Update with your actual ESP UUID
  # fileSystems."/boot" = {
  #   device = "/dev/disk/by-uuid/YOUR-ESP-UUID";
  #   fsType = "vfat";
  # };

  swapDevices = [{device = "/swap/swapfile"; size = 4096;}];

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
